### PR TITLE
Fix resource directory when using functions directory.

### LINKED ISSUE #2083: Pipeline does not execute when using "functions" dir and no input
This does not work (functions placed under special `functions` directory):
```sh
DEMO=$(mktemp -d)
FUNC_DIR=$DEMO/functions
mkdir $FUNC_DIR

cat <<EOF >$FUNC_DIR/function.yaml
apiVersion: config.kubernetes.io/v1beta1
kind: ConsulConfigFunction
metadata:
  name: my-consul-server
  annotations:
    config.kubernetes.io/function: |
      container:
        image: gcr.io/config-functions/consul:v0.0.2
EOF

kustomize config run $DEMO
```

However this does work (functions not in a special `functions` directory):
```sh
DEMO=$(mktemp -d)

cat <<EOF >$DEMO/function.yaml
apiVersion: config.kubernetes.io/v1beta1
kind: ConsulConfigFunction
metadata:
  name: my-consul-server
  annotations:
    config.kubernetes.io/function: |
      container:
        image: gcr.io/config-functions/consul:v0.0.2
EOF

kustomize config run $DEMO
```

https://github.com/kubernetes-sigs/kustomize/pull/2053

### PR DESCRIPTION
**Pull request by bzub**
Fixes #2083

### CODE REVIEW

**Comment by bzub** [comment]
Do not merge.

File: kyaml/kio/filters/container.go [hunk 1]
```diff
@@ -225,6 +225,11 @@ func (c *ContainerFilter) scope(dir string, nodes []*yaml.RNode) ([]*yaml.RNode,
 		}
 
 		resourceDir := path.Clean(path.Dir(p))
+		if path.Base(resourceDir) == functionsDirectoryName {
```
Comment (pwittrock) [inline kyaml/kio/filters/container.go]: Add the following comment:

```go
// Functions in the `functions` directory are scoped to themselves, and should see themselves as input
```
