### PR TITLE
fix name reference with prefixsuffix

### LINKED ISSUE #2609: Generated configmap hash suffix not applied to patched resource when nameSuffix or namePrefix is
Hi all. Firstly and quickly, I'm enjoying kustomize, thank you for your work.

```
$ kustomize version
Version: {Version:3.3.1 GitCommit:f2ac5a2d0df13c047fb20cbc12ef1a3b41ce2dad BuildDate:unknown GoOs:linux GoArch:amd64}
```

I also managed to reproduce with a build from master at revision `9b5ce5002a9a183ff77c57fd48b17bd021c2510d`.

I'm facing an issue where applying a `nameSuffix` or `namePrefix` to an overlay results in a patch not being applied with the `configmapKeyRef.name` or `configMapRef.name` I expected.

I reproduce the file structure below, but if you prefer you can obtain the files from: `git pull https://github.com/msk-/kustomize-issue`
Then
1. `kustomize build` in the directory root to see the unexpected output, specifically the absence of a generated suffix on the deployment `.spec.template.spec.containers[0].env[0].valueFrom.configMapKeyRef.name` and `.spec.template.spec.containers[0].envFrom[0].configMapRef.name`
2. modify `./handlers/kustomization.yaml`, remove the first line containing the `nameSuffix` field
3. `kustomize build` to see the output I had expected, sans the name `nameSuffix`

Result of step (1) above:
```yaml
apiVersion: v1
data:
  MYSQL_DATABASE: db
  MYSQL_USER: user
kind: ConfigMap
metadata:
  annotations: {}
  labels: {}
  name: mysql-h7d4485k9d
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: short-suffix
spec:
  template:
    spec:
      containers:
      - env:
        - valueFrom:
            configMapKeyRef:
              key: MYSQL_DATABASE
              name: mysql
        envFrom:
        - configMapRef:
            name: mysql
        name: handler
```

Result of step (3) above:
```yaml
apiVersion: v1
data:
  MYSQL_DATABASE: db
  MYSQL_USER: user
kind: ConfigMap
metadata:
  annotations: {}
  labels: {}
  name: mysql-h7d4485k9d
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: short
spec:
  template:
    spec:
      containers:
      - env:
        - valueFrom:
            configMapKeyRef:
              key: MYSQL_DATABASE
              name: mysql-h7d4485k9d
        envFrom:
        - configMapRef:
            name: mysql-h7d4485k9d
        name: handler
```

I note that `behavior: replace` also does not result in the hash suffix being applied. But removing the `behavior` field (and the "`mysql`" dependency) does result in a hash suffix on the config map names.

```sh
mkdir handlers mysql

cat > handlers/kustomization.yaml << EOF
nameSuffix: -suffix

resources:
  - ./deployment.yaml
EOF

cat > handlers/deployment.yaml << EOF
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: short
spec:
  template:
    spec:
      containers:
      - name: handler
EOF

cat > mysql/kustomization.yaml << EOF
configMapGenerator:
  - name: mysql
    literals:
      - MYSQL_USER=mysql
      - MYSQL_DATABASE=default
EOF

cat > kustomization.yaml << EOF
resources:
  - ./mysql
  - ./handlers

configMapGenerator:
  - name: mysql
    behavior: merge
    literals:
      - MYSQL_DATABASE=db
      - MYSQL_USER=user

patches:
  - target:
      kind: Deployment
      name: s.*
    patch: |-
      kind: Deployment
      metadata:
        name: ignored
      spec:
        template:
          spec:
            containers:
              - name: handler
                envFrom:
                  - configMapRef:
                      name: mysql
                env:
                  - valueFrom:
                      configMapKeyRef:
                        name: mysql
                        key: MYSQL_DATABASE
EOF
```

Edit: Casting around a little, this may be related: https://github.com/kubernetes-sigs/kustomize/issues/1301#issuecomment-616918795

### LINKED ISSUE #2717: namespace does not work with ClusterRoleBinding subjects when using PrefixSuffixTransformer plugin
Namespace overriding does not work with ClusterRoleBinding subjects when using PrefixSuffixTransformer plugin.

Example
workloads.yaml:
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: myapp
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: myapp
subjects:
- kind: ServiceAccount
  name: myapp

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: myapp
```

prefixSuffixTransformer.yaml:
```
apiVersion: builtin
kind: PrefixSuffixTransformer
metadata:
  name: notImportantHere
suffix: -suffix
fieldSpecs:
- path: metadata/name
  kind: ClusterRoleBinding
```

kustomization.yaml:
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- workloads.yaml
namespace: prod
transformers:
- prefixSuffixTransformer.yaml
```

Result:
```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: myapp
  namespace: prod
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: myapp-suffix
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: myapp
subjects:
- kind: ServiceAccount
  name: myapp
```
Note: there is no `namespace: prod` in `ClusterRoleBinding` `subjects`.

After removing `transformers` section from `kustomization.yaml` output looks fine:
```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: myapp
  namespace: prod
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: myapp
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: myapp
subjects:
- kind: ServiceAccount
  name: myapp
  namespace: prod
```

```
$ kustomize version
{Version:3.8.0 GitCommit:6a50372dd5686df22750b0c729adaf369fbf193c BuildDate:2020-07-05T17:55:53+01:00 GoOs:darwin GoArch:amd64}
```

### PR DESCRIPTION
**Pull request by Shell32-Natsu**
Solution: move prefix/suffix check from preparing candidates to after finding match to make sure resources that don't have match prefix/suffix can be matched.

The entire name reference implementation is still messy and too hard to understand. This solution may also affect the *performance* of name reference. We may have to refactor it.

Fix #2717 
Fix #2609

### CODE REVIEW

File: api/filters/nameref/nameref.go [hunk 1]
```diff
@@ -86,6 +86,16 @@ func (f Filter) setScalar(node *yaml.RNode) error {
 	return nil
 }
 
+func filterReferralCandidates(referrer *resource.Resource, matches []*resource.Resource) []*resource.Resource {
+	ret := []*resource.Resource{}
```
Comment (monopole) [inline api/filters/nameref/nameref.go:90]: FWIW, this can be just
```
var ret []*resource.Resource
```
No need actually allocate the array.  `append` will do the right thing.

**Comment by monopole** [comment]
Thanks for taking this on, it's tricky.
I think it's the right approach.
Please add test coverage to protect against regression and so we can be more confident about this.

**Comment by monopole** [comment]
@Shell32-Natsu in the PR description above, can you add  `F\ixes #0000` but leave out the `\` and use the right number?

https://docs.github.com/en/github/writing-on-github/autolinked-references-and-urls#issues-and-pull-requests

**Comment by Shell32-Natsu** [comment]
@monopole Done
