### PR TITLE
fix: add namespace option to 'edit add configmap' command

### LINKED ISSUE #5366: kustomize edit add configmap does not support specifying namespace
### What happened?

When trying to create a `configMapGenerator` via `kustomize edit add configmap`, it is not possible to specify a namespace for that resource. Running the following command:
```shell
kustomize edit add configmap test-cm --namespace test-ns --from-literal=testkey=testvalue
```

will output
```console
Error: unknown flag: --namespace
```

However, editing the kustomization file to add a namespace, like so:
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
- literals:
  - testkey=testvalue
  name: test-cm
  namespace: test-ns
```

then running `kustomize build` results in a ConfigMap configuration containing a namespace:
```shell
kustomize build .
```

```yaml
apiVersion: v1
data:
  testkey: testvalue
kind: ConfigMap
metadata:
  name: test-cm-bgk86k8k5t
  namespace: test-ns
```

### What did you expect to happen?

A namespace gets added to the `configMapGenerator`.

### How can we reproduce it (as minimally and precisely as possible)?

Just running

```shell
kustomize edit add configmap test-cm --namespace test-ns --from-literal=testkey=testvalue
```

will demonstrate the issue.

### Expected output

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
- literals:
  - testkey=test-value
  name: test-cm
  namespace: test-ns
```

### Actual output

```console
Error: unknown flag: --namespace
```

### Kustomize version

v5.1.1

### Operating system

MacOS

### PR DESCRIPTION
**Pull request by stormqueen1990**
* Add option to include a namespace when adding a ConfigMap via `kustomize edit add configmap` command.
* Refactor the constants for flag names to keep a standard between them.
* Update comment for `GeneratorArgs` to reflect the usage of the `Namespace` field.

Fixes #5366

### CODE REVIEW

File: kustomize/commands/edit/add/configmap.go [hunk 1]
```diff
@@ -36,7 +36,10 @@ func newCmdAddConfigMap(
 	kustomize edit add configmap my-configmap --from-env-file=env/path.env
 
 	# Adds a configmap from env-file with behavior merge
-	kustomize edit add configmap my-configmap --behavior=merge --from-env-file=env/path.env	
+	kustomize edit add configmap my-configmap --behavior=merge --from-env-file=env/path.env
+
+    # Adds a configmap to the kustomization file with a specific namespace
+    kustomize edit add configmap my-configmap --namespace test-ns --from-literal=my-key=my-value
```
Comment (charles-chenzz) [inline kustomize/commands/edit/add/configmap.go:42]: nit: 
image

**Review by charles-chenzz — APPROVED** [review]
except the format, other LGTM

**Comment by natasha41575** [comment]
/hold so you can address https://github.com/kubernetes-sigs/kustomize/pull/5367#discussion_r1357826716

Feel free to remove the hold whenever you are ready to merge (and you can ping for another LGTM if needed)

/lgtm
approve

**Review by natasha41575 — APPROVED** [review]

File: kustomize/commands/edit/add/configmap.go (hunk 1 above)
Comment (stormqueen1990) [reply kustomize/commands/edit/add/configmap.go]: Tabs vs. spaces got me 😅
Thanks for spotting this 🙏 just fixed!

**Review by charles-chenzz — APPROVED** [review]
/lgtm
