### PR TITLE
Fix issues with replacements

### LINKED ISSUE #3927: Replacements transformer overwrites source field (when multiple fieldPaths are specified?)
**Describe the bug**

When using the new Replacements transformer with multiple target `fieldPaths` in the same target yaml array, the transformer transforms not only the target field, but the source field as well. (I did not test with other targets like maps, just sequences.)

This appears to occur iteratively, once for each entry in `fieldPaths`. This results in the target transformation also being incorrect, with the replacement repeated. See actual output below.

**Files that can reproduce the issue**

Files to reproduce the issue are here: https://github.com/jameshochadel/kustomize-replacements/tree/main/repeat

**Expected output**

```
apiVersion: v1
data:
  value: example
kind: ConfigMap
metadata:
  name: source
---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: some-secret
spec:
  backendType: secretsManager
  data:
  - key: some-prefix-example
    name: first
    property: first
    version: latest
  - key: some-prefix-example
    name: second
    property: second
    version: latest
  - key: some-prefix-example
    name: third
    property: third
    version: latest
```

**Actual output**

```
apiVersion: v1
data:
  value: some-prefix-some-prefix-some-prefix-example
kind: ConfigMap
metadata:
  name: source
---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: some-secret
spec:
  backendType: secretsManager
  data:
  - key: some-prefix-example
    name: first
    property: first
    version: latest
  - key: some-prefix-some-prefix-example
    name: second
    property: second
    version: latest
  - key: some-prefix-some-prefix-some-prefix-example
    name: third
    property: third
    version: latest
```

**Kustomize version**

{Version:kustomize/v4.1.3 GitCommit:0f614e92f72f1b938a9171b964d90b197ca8fb68 BuildDate:2021-05-20T20:52:40Z GoOs:darwin GoArch:amd64}

**Platform**

macOS

**Additional context**

n/a. But, bugs aside, huge thanks to the team for adding this transformer! I'm very excited to replace our `vars` usages with this.

### LINKED ISSUE #3928: Replacements transformer list indexing fails for keys with '.' character
**Describe the bug**

The new Replacements transformer's `fieldPaths` supports two ways of specifying elements in a list:

1. By index, like `spec.data.0.field`, or
2. By key, like `spec.data.[name=something].field`. 

The second method works for most strings, but if the string contains a `.` character, kustomize seems to try parsing it like it's one of the field accessors, rather than part of the selector.

**Files that can reproduce the issue**

Files to reproduce are here: https://github.com/jameshochadel/kustomize-replacements/tree/main/dotfile

**Expected output**

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: source
data:
  value: example
---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: some-secret
spec:
  backendType: secretsManager
  data:
    - key: some-prefix-example
      name: .first
      version: latest
      property: first
    - key: some-prefix-example
      name: second
      version: latest
      property: second
```

**Actual output**

```
Error: wrong Node Kind for spec.data expected: MappingNode was SequenceNode: value: {- key: some-prefix-replaceme
  name: .first
  version: latest
  property: first
- key: some-prefix-replaceme
  name: second
  version: latest
  property: second}
```

**Kustomize version**

{Version:kustomize/v4.1.3 GitCommit:0f614e92f72f1b938a9171b964d90b197ca8fb68 BuildDate:2021-05-20T20:52:40Z GoOs:darwin GoArch:amd64}

**Platform**

macOS

**Additional context**

n/a (but thanks again for all you do!)

### PR DESCRIPTION
**Pull request by natasha41575**
First commit demonstrates #3927, second demonstrates #3928.

Third commit fixes #3927, fourth fixes #3928.

### CODE REVIEW

File: api/filters/replacement/replacement.go [hunk 1]
```diff
@@ -178,3 +178,27 @@ func makeResId(n *yaml.RNode) *resid.ResId {
 		Namespace: n.GetNamespace(),
 	}
 }
+
+func getFieldPath(fieldPath string) []string {
```
Comment (KnVerey) [inline api/filters/replacement/replacement.go:182]: Does this belong in kyaml? The features we're supporting here don't really belong to the ReplacementTranformer so much as yaml.PathGetter. Maybe what we want is a variant on the `LookupCreate` PathGetter initializer that takes a raw structured string? Or just a parser helper function to use with the existing LookupCreate.

Comment (monopole) [inline api/filters/replacement/replacement.go:182]: Please 

 - move this function to https://github.com/kubernetes-sigs/kustomize/blob/master/api/internal/utils/pathsplitter.go alongside the func called PathSplitter.
 - call it `SmarterPathSplitter` to distinguish it from `PathSplitter`.
 - optionally pass the delimitter, so we can pass `'.'` or `'/'` (pass a byte, not a string, so we can someday respect escaping of the delimiter)
 

Comment could be:

```
// SmarterPathSplitter splits a path, retaining bracketed list entry identifiers.
// E.g. [name=com.foo.someapp] survives as one thing after splitting
// "spec.template.spec.containers.[name=com.foo.someapp].image"
// See kyaml/yaml/match.go for use of list entry identifiers.
// TODO combine with `PathSplitter`, so one function both respects list entry identifiers
// and escaped delimiters
```

Comment (natasha41575) [reply api/filters/replacement/replacement.go:182]: You're right that this logic makes more sense in kyaml. I'll move it.

File: api/filters/replacement/replacement.go [hunk 2]
```diff
@@ -78,7 +78,7 @@ func applyToNode(node *yaml.RNode, value *yaml.RNode, target *types.TargetSelect
 			return err
 		}
 		if t != nil {
-			if err = setTargetValue(target.Options, t, value); err != nil {
+			if err = setTargetValue(target.Options, t, value.Copy()); err != nil {
```
[the remark this answers is not in the document]
Comment (natasha41575) [reply api/filters/replacement/replacement.go:81]: will do

File: api/filters/replacement/replacement.go [hunk 3]
```diff
@@ -178,3 +178,27 @@ func makeResId(n *yaml.RNode) *resid.ResId {
...
+
+func getFieldPath(fieldPath string) []string {
+	var result []string
+	split := strings.Split(fieldPath, ".")
+
+	for i := 0; i < len(split); i = i + 1 {
+		elem := split[i]
+		if strings.HasPrefix(elem, "[") && !strings.HasSuffix(elem, "]") {
+			// continue until we find the matching "]"
+			sequenceIndex := []string{elem}
```
Comment (monopole) [inline api/filters/replacement/replacement.go:190]: `s/sequenceIndex/bracketed/`

File: api/filters/replacement/replacement.go [hunk 4]
```diff
@@ -178,3 +178,27 @@ func makeResId(n *yaml.RNode) *resid.ResId {
 		Namespace: n.GetNamespace(),
 	}
 }
+
+func getFieldPath(fieldPath string) []string {
+	var result []string
+	split := strings.Split(fieldPath, ".")
+
+	for i := 0; i < len(split); i = i + 1 {
```
Comment (monopole) [inline api/filters/replacement/replacement.go:186]: `; i++ {`

File: api/filters/replacement/replacement_test.go [hunk 5]
```diff
@@ -1439,3 +1505,48 @@ spec:
...
+		},
+	}
+	for tn, tc := range testCases {
+		t.Run(tn, func(t *testing.T) {
+			assert.True(t, stringSliceEquals(tc.expected, getFieldPath(tc.input)))
+		})
+	}
+}
+
+func stringSliceEquals(a []string, b []string) bool {
```
Comment (monopole) [inline api/filters/replacement/replacement_test.go:1542]: shouldn't need this

File: api/filters/replacement/replacement.go (hunk 1 above)
Comment (monopole) [reply api/filters/replacement/replacement.go:182]: I just saw @KnVerey 's comment.

before moving to kyaml, please first combine it with the existing PathSplitter somehow (respected escaping) and then move it.   perhaps in a distinctr Pr after this.

Another possible home for this splitter (these functions) is as a method on the FieldSpec object.

Comment (monopole) [reply api/filters/replacement/replacement.go:182]: BTW, `SmarterPathSplitter` is silly, but `ListEntryIdentifierAwarePathSplitter` is a bit long.

I'd prefer just to have one pathsplitter to avoid making up a new name :)

**Comment by monopole** [comment]
@natasha41575 _Excellent job_ in the first commit establishing issue behavior, and then fixing it in a subsequent commit.

File: api/filters/replacement/replacement.go (hunk 4 above)
Comment (natasha41575) [reply api/filters/replacement/replacement.go:186]: for some reason I assumed you couldn't do this in go :) glad I was mistaken

File: api/filters/replacement/replacement.go [hunk 6]
```diff
@@ -142,9 +142,8 @@ func getRefinedValue(options *types.FieldOptions, rn *yaml.RNode) (*yaml.RNode,
 	if options.Index >= len(value) || options.Index < 0 {
 		return nil, fmt.Errorf("options.index %d is out of bounds for value %s", options.Index, yaml.GetValue(rn))
 	}
-	n := rn.Copy()
-	n.YNode().Value = value[options.Index]
-	return n, nil
+	rn.YNode().Value = value[options.Index]
```
[the remark this answers is not in the document]
Comment (natasha41575) [reply api/filters/replacement/replacement.go]: done

File: api/filters/replacement/replacement.go (hunk 1 above)
Comment (natasha41575) [reply api/filters/replacement/replacement.go]: Will move the logic to kyaml in a followup PR

Comment (natasha41575) [reply api/filters/replacement/replacement.go]: I moved it to api/internal/utils/pathsplitter.go and also had it use the existing `PathSplitter` so that SmarterPathSplitter respects both bracketed list elements as well as escaped delimiters. I'll move it to kyaml in a follow-up.

**Comment by monopole** [comment]
/lgtm
Thanks!

**Comment by 616b2f** [comment]
Does it also fixes this kind of issues:

```
source:
  kind: ConfigMap
  name: my-config
  fieldPath: data.my-var
targets:
- select:
    name: my-service
    kind: Service
  fieldPaths:
  - metadata.annotations.["service.beta.kubernetes.io/load-balancer-abc"]
```

Because this also does not seem to work with kustomize v4.1.3

**Comment by natasha41575** [comment]
@616b2f No it does not. I will work on that. Filed a tracking issue https://github.com/kubernetes-sigs/kustomize/issues/3983, thank you for using and trying out the feature!

**Comment by natasha41575** [comment]
@616b2f just as an FYI this PR does provide functionality to escape our delimiters, e.g. `service\.beta\.kubernetes\.io/load-balancer-abc`, but I have also submitted [another PR](https://github.com/kubernetes-sigs/kustomize/pull/3984) so that you can use surrounding brackets too.

**Comment by 616b2f** [comment]
@natasha41575 thank you for clarification and opening the new bug.

Btw. I love the new feature you implemented, it's really saved us a lot of pain.
