### PR TITLE
Reinstate configmap/secret generator 'env' field.

### LINKED ISSUE #2205: `kubectl apply -k` vs `kustomize build` "env" and "envs" error
Hi,

I'm trying to simplify the structures of my yaml files. I segregated the common configs and secrets so I can re-use it into my deployment manifests.

I used:
```
# sample file.yaml
configMapGenerator:
   name: my-config 
   envs: #env
       - config.env
```

Then I ran:
```
$ kubectl apply -k .

error: AccumulateTarget: couldn't make target for path/to/config/folder: json: unknown field "envs"
couldn't make target for path/to/config/folder: json: unknown field "envs"

AccumulateTarget: couldn't make target for base: json: unknown field "envs"
```

After changing it from `envs` to `env` then ran:
```
$ kustomize build .

Error: accumulating resources: recursed accumulation of path 'path/to/configs/folder': accumulating resources: couldn't make target for path 'path/to/configs/folder/subfolder': json: unknown field "env"
```

### PR DESCRIPTION
**Pull request by monopole**
Fixes #2205 
This field was overzealously deprecated.

### CODE REVIEW

File: api/types/kustomization_test.go [hunk 1]
```diff
@@ -15,6 +16,12 @@ func fixKustomizationPostUnmarshallingCheck(k, e *Kustomization) bool {
 func TestFixKustomizationPostUnmarshalling(t *testing.T) {
 	var k Kustomization
 	k.Bases = append(k.Bases, "foo")
+	k.ConfigMapGenerator = []ConfigMapArgs{{GeneratorArgs{
+		KvPairSources: KvPairSources{
+			EnvSources: []string{"a", "b"},
+			EnvSource:  "c",
+		},
+	}}}
 	k.FixKustomizationPostUnmarshalling()
```
Comment (KnVerey) [inline api/types/kustomization_test.go:25]: Suggestions: 
- Should we update `fixKustomizationPostUnmarshallingCheck` to verify that `EnvSource` (singular) has been cleared?
- Both this test and the one in kusty/configmaps_test show the fix working for configmap generator. Should we add coverage for secret generator as well?

**Review by KnVerey — APPROVED** [review]
I noticed that this repo has schemas for kustomization in `kyaml/openapi/kustomizationapi`. Do those need to be updated to reflect this field?

/lgtm

File: api/types/kustomization_test.go (hunk 1 above)
Comment (monopole) [reply api/types/kustomization_test.go:25]: great comments

- re: `fixKustomizationPostUnmarshallingCheck`;   Since this PR added a deepequal reflection test,  fixKustomizationPostUnmarshallingCheck is arguably a redundant and weaker condition.     I left it in so that it didn't appear that the PR was reducing coverage.  Probably should have deleted it, or used it instead of deepequals.

- one cannot see it unless one expands all the lines, but the modified krusty test does cover secret behavior - see
https://github.com/kubernetes-sigs/kustomize/pull/3692/files#diff-a497b67d0a86cac8b63450bff25432f185a5bab7413ba04f67212a7d36241cffL146
https://github.com/kubernetes-sigs/kustomize/pull/3692/files#diff-a497b67d0a86cac8b63450bff25432f185a5bab7413ba04f67212a7d36241cffR219

**Comment by monopole** [comment]
> I noticed that this repo has schemas for kustomization in `kyaml/openapi/kustomizationapi`. Do those need to be updated to reflect this field?

yes, filed #3698
it's not urgent for kubectl reintegration - kustomize doesn't actually use that spec.
