### PR TITLE
fixed issue 2896

### LINKED ISSUE #2896: Kustomize Doesn't append nameSuffix from base when patch is applied to derived file in version 3.8.1
Hi Here's an example: 
My base app under `./base/test-api/` directory has these two files:
deployment.yaml
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example
spec:
  template:
    spec:
      containers:
        - name: example
          image: example:1.0
          volumeMounts:
            - name: conf
              mountPath: /etc/config
      volumes:
        - name: conf
          configMap:
            name: conf
```

kustomization.yaml
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -test-api

resources:
 - deployment.yaml
```

Here's how my derived app kustomization file looks like under `./overlays/derived`:
kustomization.yaml
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


resources:
  - ../../base/test-api


patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: example
      spec:
        template:
          spec:
            containers:
             - name: example
               image: example:2.0

```

When I try to run the command:
`kustomize build --load_restrictor none overlays/derived/`

I get this output:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example
spec:
  template:
    spec:
      containers:
      - image: example:2.0
        name: example
        volumeMounts:
        - mountPath: /etc/config
          name: conf
      volumes:
      - configMap:
          name: conf
        name: conf
```

While if I use version 3.7.0; I get this output:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-test-api
spec:
  template:
    spec:
      containers:
      - image: example:2.0
        name: example
        volumeMounts:
        - mountPath: /etc/config
          name: conf
      volumes:
      - configMap:
          name: conf
        name: conf
```

As you can see from the above two output, the nameSuffix is not appended to the output in version 3.8.1 while it is being appended to version 3.7.0. Has anything changed from 3.7.0 to 3.8.1 to cause this bug or is it intended behavior?

### PR DESCRIPTION
**Pull request by natasha41575**
fix #2896

### CODE REVIEW

File: plugin/builtin/patchtransformer/PatchTransformer.go [hunk 1]
```diff
@@ -143,9 +143,12 @@ func (p *plugin) applySMPatch(resource, patch *resource.Resource) error {
 	if err != nil {
 		return err
 	}
-	return filtersutil.ApplyToJSON(patchstrategicmerge.Filter{
+	n := resource.GetName()
```
Comment (Shell32-Natsu) [inline plugin/builtin/patchtransformer/PatchTransformer.go:146]: PatchTarget doesn't only contain name but also namespace.

https://github.com/kubernetes-sigs/kustomize/blob/45893b258899b5adaada80a29e59770afcdf3143/api/types/patchtarget.go#L11-L15

**Review by Shell32-Natsu — CHANGES_REQUESTED** [review]

File: plugin/builtin/patchtransformer/PatchTransformer.go (hunk 1 above)
Comment (natasha41575) [reply plugin/builtin/patchtransformer/PatchTransformer.go:146]: So should we save the old namespace as well, in addition to the name? Anything else I should save? I think in meeting you also mentioned saving the GVK

Comment (Shell32-Natsu) [reply plugin/builtin/patchtransformer/PatchTransformer.go:146]: GVK is probably not needed since the patch shouldn't have different GVK otherwise it won't match the target. The reason that we need name and namespace is name and namespace can be modified in the pipeline and the name/namespace may be the old one in the patch.

Comment (natasha41575) [reply plugin/builtin/patchtransformer/PatchTransformer.go]: updated to include namespace

File: plugin/builtin/patchtransformer/PatchTransformer.go [hunk 2]
```diff
@@ -143,9 +143,15 @@ func (p *plugin) applySMPatch(resource, patch *resource.Resource) error {
 	if err != nil {
 		return err
 	}
-	return filtersutil.ApplyToJSON(patchstrategicmerge.Filter{
+	n, ns := resource.GetName(), resource.GetNamespace()
+	err = filtersutil.ApplyToJSON(patchstrategicmerge.Filter{
 		Patch: node,
 	}, resource)
+	if resource.GetName() != "" {
```
Comment (Shell32-Natsu) [inline plugin/builtin/patchtransformer/PatchTransformer.go:150]: @monopole Do we have a method in `Resource` to check is the resource empty?

Comment (Shell32-Natsu) [reply plugin/builtin/patchtransformer/PatchTransformer.go:150]: I don't find it in the code but maybe I miss something.

Comment (natasha41575) [reply plugin/builtin/patchtransformer/PatchTransformer.go:150]: I also was looking for something like that but didn't find it which is why I did this instead. I may also have missed something.

Comment (monopole) [reply plugin/builtin/patchtransformer/PatchTransformer.go:150]: We don't have that concept.

namespace is optional, but kind, apiVersion and metadata/name are not.  An empty name makes the `kustomize build`, and moreover, the apiserver demands names too.

I think all we need here are the writes.  Restore the old values without even looking at them.
i.e. no `if` statement

Comment (monopole) [reply plugin/builtin/patchtransformer/PatchTransformer.go:150]: I'm tempted to blindly restore the value of the `kind` and `apiVersion` fields as well, but we don't have a specific mutator for them like we do for the `metadata/name` field.

Comment (natasha41575) [reply plugin/builtin/patchtransformer/PatchTransformer.go:150]: Removing the if statement causes the TestPatchTransformerWithPatchDelete test to fail, which is why I added it. What do you want to do for that test case?

Comment (monopole) [reply plugin/builtin/patchtransformer/PatchTransformer.go:150]: Sigh.  Yes, the deletion hack.  So we need the test, and now i better understand what @Shell32-Natsu was hinting at - we can have an invalid (deleted but zombie-like) resource come in here, and we shouldn't mess with it.

Comment (monopole) [reply plugin/builtin/patchtransformer/PatchTransformer.go:150]: `L125 if len(res.Map()) == 0 {`
is the closest thing we have to an "IsEmpty" test.
So we could test that here, which would be clearer thant just looking at the name field.
i'm also curious if it would work.
then in a later PR someone could introduce IsEmpty on the Resource interface, and use it everywhere where we test the length of the Map().

Comment (natasha41575) [reply plugin/builtin/patchtransformer/PatchTransformer.go]: updated

**Review by monopole — APPROVED** [review]
/lgtm
