### PR TITLE
filter by namespace, prefix and detect conflict when resolving name reference

### LINKED ISSUE #293: Combining multiple overlays of the same base with different prefixes breaks name reference
I have a base Kustomization for an application. I have several overlays based on it with different name prefixes. I then combine those into another Kustomization.

Name references are not resolved properly when multiple prefixes are in play. Sometimes, a name reference will point to the name from its sibling Kustomization.

The repo https://github.com/mxey/kustomize-nameprefix-reproduction contains the files to reproduce this.

output of `kustomize build combined`:

```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: b-serviceaccount
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: a-serviceaccount
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: a-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: role
subjects:
- kind: ServiceAccount
  name: b-serviceaccount
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: b-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: role
subjects:
- kind: ServiceAccount
  name: b-serviceaccount
```

As you can see, the `a-rolebinding` has the `b-serviceaccount` as its subject. 

This does not happen for every run, I assume it is basically random which resource is selected depending on the hashing for Go maps.

### PR DESCRIPTION
**Pull request by Liujingfang1**
Fix #293 

This change can resolve name reference in multi bases correctly as well as detecting conflicts
Also added two tests. One is with conflict, the other without.

### CODE REVIEW

File: pkg/resource/resid.go [hunk 1]
```diff
@@ -97,10 +97,25 @@ func (n ResId) Namespace() string {
...
 // CopyWithNewNamespace make a new copy from current ResId and set a new namespace
 func (n ResId) CopyWithNewNamespace(ns string) ResId {
 	return ResId{gvk: n.gvk, name: n.name, prefix: n.prefix, namespace: ns}
 }
+
+// HasSamePrefix check if two ResIds have the same prefix
+func (n ResId) HasSamePrefix(id ResId) bool {
+	if id.prefix == "" {
+		return true
+	}
```
Comment (monopole) [inline pkg/resource/resid.go]: look odd.  

comment needs fixing.  what if n.prefix isn't empty?

maybe use properPrefix instead?

I'm not in love with the name properPrefix - feel free to improve

File: pkg/resource/resid.go [hunk 2]
```diff
@@ -97,10 +97,25 @@ func (n ResId) Namespace() string {
 
 // CopyWithNewPrefix make a new copy from current ResId and append a new prefix
 func (n ResId) CopyWithNewPrefix(p string) ResId {
+	if p != "" && n.prefix != "" {
+		return ResId{gvk: n.gvk, name: n.name, prefix: p + ":" + n.prefix, namespace: n.namespace}
+	}
```
Comment (monopole) [inline pkg/resource/resid.go]: readability:
```
func (n ResId) properPrefix(p string) string {
  if p == "" || n.prefix == "" {
    return p + n.prefix
  }
  return p + ":" + n.prefix
}
...
return ResId{gvk: n.gvk, name: n.name, prefix: n.fixPrefix(p), namespace: n.namespace}
```

Can properPrefix be used in FilterBy ?

Comment (Liujingfang1) [reply pkg/resource/resid.go]: I name the function as `concatePrefix`.
Since this function manipulate a string given another string, we couldn't use this function directly in `FilterBy`. In `FilterBy`, we need a function to compare the leading part of two prefixes.

File: pkg/resource/resid.go (hunk 1 above)
Comment (Liujingfang1) [reply pkg/resource/resid.go]: I added a function `prefixList` and used it here.

File: pkg/commands/testdata/testcase-multibases-conflict/base/kustomization.yaml [hunk 3]
```diff
@@ -0,0 +1,4 @@
+resources:
+- serviceaccount.yaml
+- rolebinding.yaml
+namePrefix: base-
```
Comment (monopole) [inline pkg/commands/testdata/testcase-multibases-conflict/base/kustomization.yaml]: please add EOL

File: pkg/commands/testdata/testcase-multibases-conflict/overlays/a/kustomization.yaml [hunk 4]
```diff
@@ -0,0 +1,7 @@
+bases:
+- ../../base/
+
+namePrefix: a-
+
+resources:
+- serviceaccount.yaml
```
Comment (monopole) [inline pkg/commands/testdata/testcase-multibases-conflict/overlays/a/kustomization.yaml]: please add EOL

File: pkg/commands/testdata/testcase-multibases-nonconflict/base/kustomization.yaml [hunk 5]
```diff
@@ -0,0 +1,4 @@
+resources:
+- serviceaccount.yaml
+- rolebinding.yaml
+namePrefix: base-
```
Comment (monopole) [inline pkg/commands/testdata/testcase-multibases-nonconflict/base/kustomization.yaml]: please add EOL

File: pkg/resource/resid.go [hunk 6]
```diff
@@ -97,10 +97,35 @@ func (n ResId) Namespace() string {
...
 }
+
+// HasSamePrefix check if two ResIds have the same leading prefix
+func (n ResId) HasSamePrefix(id ResId) bool {
+	prefixes1 := n.prefixList()
+	prefixes2 := id.prefixList()
+	return len(prefixes1) == 0 || len(prefixes2) == 0 || prefixes1[0] == prefixes2[0]
+}
+
+func (n ResId) concatePrefix(p string) string {
```
Comment (monopole) [inline pkg/resource/resid.go]: concat

File: pkg/resource/resid.go [hunk 7]
```diff
@@ -97,10 +97,35 @@ func (n ResId) Namespace() string {
...
-	return ResId{gvk: n.gvk, name: n.name, prefix: p + n.prefix, namespace: n.namespace}
+	return ResId{gvk: n.gvk, name: n.name, prefix: n.concatePrefix(p), namespace: n.namespace}
 }
 
 // CopyWithNewNamespace make a new copy from current ResId and set a new namespace
 func (n ResId) CopyWithNewNamespace(ns string) ResId {
 	return ResId{gvk: n.gvk, name: n.name, prefix: n.prefix, namespace: ns}
 }
+
+// HasSamePrefix check if two ResIds have the same leading prefix
```
Comment (monopole) [inline pkg/resource/resid.go]: This comment suggests that this is some kind of equals method.  It's much odder than that.

Please elaborate on the empty string checks and the check of only the first element in the comment, especially since this is a public method.

Perhaps rename to HasSameEffectivePrefix ?

Comment (Liujingfang1) [reply pkg/resource/resid.go]: Naming is always hard. `HasSameEffectivePrefix` sounds better than `HasSamePrefix`. 
 I'll come up with a good comment of this function.

Comment (Liujingfang1) [reply pkg/resource/resid.go]: I found that we could get rid the special case for empty prefix. The new change looks more clean.

File: pkg/resource/resid.go [hunk 8]
```diff
@@ -97,10 +97,32 @@ func (n ResId) Namespace() string {
...
-	return ResId{gvk: n.gvk, name: n.name, prefix: p + n.prefix, namespace: n.namespace}
+	return ResId{gvk: n.gvk, name: n.name, prefix: n.concatPrefix(p), namespace: n.namespace}
 }
 
 // CopyWithNewNamespace make a new copy from current ResId and set a new namespace
 func (n ResId) CopyWithNewNamespace(ns string) ResId {
 	return ResId{gvk: n.gvk, name: n.name, prefix: n.prefix, namespace: ns}
 }
+
+// HasSameEffectivePrefix check if two ResIds have the same
```
Comment (monopole) [inline pkg/resource/resid.go]: HasSameLeftmostPrefix !!!

File: pkg/resource/resid.go [hunk 9]
```diff
@@ -97,10 +97,32 @@ func (n ResId) Namespace() string {
...
+// left most prefix.
+func (n ResId) HasSameEffectivePrefix(id ResId) bool {
```
Comment (monopole) [inline pkg/resource/resid.go]: HasSameLeftmostPrefix !!!
