### PR TITLE
Fix loader loader when run from gopath

### LINKED ISSUE #282: Kustomize broken when run from within go path
`isRepoUrl` function returns true for paths that contain `.com` or `.org`.

for example `/go/src/github.com/myorg/myrepo/`

https://github.com/kubernetes-sigs/kustomize/blob/aff09b11085bc18915a23b332de93ec156c2dda3/pkg/loader/githubloader.go#L78

error:

```
Error: loadResMapFromBasesAndResources: couldn't make app for ../../base: open /tmp/base/kustomization.yaml: no such file or directory
```

### PR DESCRIPTION
**Pull request by emosbaugh**
`kustomize build` fails when running from a working directory within a gopath or any path with a `.org` or `.com` in for that matter.

```
base/kustomization.yaml
overlays/production/kustomization.yaml
overlays/staging/kustomization.yaml
```

```
$ kustomize build ./overlays/staging
Error: loadResMapFromBasesAndResources: couldn't make app for ../../base: open /tmp/base/kustomization.yaml: no such file or directory
```

Fixes #282

### CODE REVIEW

File: pkg/loader/githubloader.go [hunk 1]
```diff
@@ -74,8 +74,15 @@ func newGithubLoader(repoUrl string, fs fs.FileSystem) (*githubLoader, error) {
 }
 
 // isRepoUrl checks if a string is a repo Url
-func isRepoUrl(s string) bool {
-	return strings.Contains(s, ".com") || strings.Contains(s, ".org") || strings.Contains(s, "https://")
+func isRepoUrl(s string, fs fs.FileSystem) bool {
```
Comment (Liujingfang1) [inline pkg/loader/githubloader.go]: Can you move the change into another function like `isLocalTarget` and leave `isRepoUrl` unchanged?

File: pkg/loader/loader.go [hunk 2]
```diff
@@ -43,7 +43,7 @@ func NewLoader(target, r string, fSys fs.FileSystem) (Loader, error) {
 		return nil, fmt.Errorf("Not valid path: root='%s', loc='%s'\n", r, target)
 	}
 
-	if isRepoUrl(target) {
+	if isRepoUrl(target, fSys) {
```
Comment (Liujingfang1) [inline pkg/loader/loader.go]: Here you can change it to
`if !isLocalTarget && isRepoUrl `

**Comment by emosbaugh** [comment]
@Liujingfang1 changes made

**Comment by Liujingfang1** [comment]
/lgtm

Can you squash comments? Then we can merge it.

**Comment by emosbaugh** [comment]
@Liujingfang1 squashed and rebased
