### PR TITLE
Fix using same helm chart with different versions

### LINKED ISSUE #4813: helmCharts does not support 1+ instances of same chart, with different versions
**Describe the bug**

When I define multiple chart instances in `helmCharts` for same chart but with different versions, the first version defined is pulled and used for all instances.

**Files that can reproduce the issue**

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: podinfo

helmCharts:
  - name: podinfo
    repo: https://stefanprodan.github.io/podinfo
    version: 6.2.1
    releaseName: podinfo1
  - name: podinfo
    repo: https://stefanprodan.github.io/podinfo
    version: 6.1.8                                      # <------ same chart, different version
    releaseName: podinfo2
```

**Expected output**

For the supplied `kustomization.yaml` we should see two Deployment resources with different images, but we do not.

**Actual output**

For the supplied `kustomization.yaml` we see two Deployment resources with matching images.

To verify:

```
$ kustomize build --enable-helm | grep -E 'image:.*podinfo'
        image: ghcr.io/stefanprodan/podinfo:6.2.1
        image: ghcr.io/stefanprodan/podinfo:6.2.1
```

**Versions**

Kustomize version: 4.5.7

Helm version: 3.9.4

**Platform**

I don't believe it's relevant, but I am on Mac.

**Additional context**

Since kustomize has a `--helm-command` I wrote a wrapper to inspect the `helm` executions made by kustomize.

Here are the executions:

```
helm version -c --short
helm pull --untar --untardir ./charts --repo https://stefanprodan.github.io/podinfo podinfo --version 6.2.1
helm template podinfo1 ./charts/podinfo --values .../kustomize-helm-3061748730/podinfo-kustomize-values.yaml
helm version -c --short
helm template podinfo2 ./charts/podinfo --values .../kustomize-helm-3953294510/podinfo-kustomize-values.yaml
```

Observerations:

- only 1 `helm pull` of the 1st version, untarred to unversioned path
- two `helm template` execs on the unversioned chart location

I conclude this is not a Helm issue, but a Kustomize issue.

Suggested fix: add the version to the chart directory (eg `podinfo-6.2.1`) and use the versioned dir in the `helm template` execs.

Regards.

### PR DESCRIPTION
**Pull request by dlish**
Fixes #4813

When a helm chart version is specified it sets `--untardir` to include `name-version` i.e. `charts/terraform-1.1.2`. 

If no version is specified the behavior stays the same in that it pulls the latest version with `--untardir` set to the charts directory ex.`charts`

### Example

```yaml
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: terraform
    releaseName: terraform-1
    namespace: terraform-1
    repo: https://helm.releases.hashicorp.com
  - name: terraform
    version: 1.1.1
    releaseName: terraform-2
    namespace: terraform-2
    repo: https://helm.releases.hashicorp.com
  - name: terraform
    version: 1.1.1
    releaseName: terraform-3
    namespace: terraform-3
    repo: https://helm.releases.hashicorp.com
  - name: terraform
    version: 1.1.2
    releaseName: terraform-4
    namespace: terraform-4
    repo: https://helm.releases.hashicorp.com
```

Running `kustomize build --enable-helm` produces the following in the `charts` directory

```
❯ tree -L 3 charts
charts
├── terraform
...
│   ├── Chart.yaml
...
│   ├── templates
...
│   └── values.yaml
├── terraform-1.1.1
│   ├── terraform
...
│   │   ├── Chart.yaml
...
│   │   ├── templates
...
│   │   └── values.yaml
│   └── terraform-1.1.1.tgz
├── terraform-1.1.2
│   ├── terraform
...
│   │   ├── Chart.yaml
...
│   │   ├── templates
...
│   │   └── values.yaml
│   └── terraform-1.1.2.tgz
└── terraform-1.1.2.tgz
```

### CODE REVIEW

**Comment by natasha41575** [comment]
> When a helm chart version is specified it sets --untardir to include name-version i.e. charts/terraform-1.1.2.
> 
> If no version is specified the behavior stays the same in that it pulls the latest version with --untardir set to the charts directory ex.charts

I have not looked at the code yet but this sounds like correct behavior and will fix https://github.com/kubernetes-sigs/kustomize/issues/4813 in the same way that I'd imagined fixing it. 

/triage accepted
/ok-to-test

/cc @koba1t @annasong20 could one of you give this a review?

**Comment by koba1t** [comment]
> Looks like there's been a number of changes to the HelmChartInflationGenerator.go file since I initially opened. I'll work on getting this PR updated

Thanks!
 I'll wait for your update.

/priority important-soon

**Comment by dlish** [comment]
Ok I think my latest update should be good for review

**Comment by koba1t** [comment]
@dlish 

This PR looks almost good!
 
I have only one comment.
Could you add e2e tests checking for #4813 fixed?

**Comment by dlish** [comment]
sounds good will get that added

**Comment by dlish** [comment]
Added that test, let me know if you think there's a better way to go about it. Thanks!

File: plugin/builtin/helmchartinflationgenerator/HelmChartInflationGenerator.go [hunk 1]
```diff
@@ -98,6 +98,11 @@ func (p *plugin) validateArgs() (err error) {
 	// disabled).
 	if p.ValuesFile == "" {
 		p.ValuesFile = filepath.Join(p.ChartHome, p.Name, "values.yaml")
+
+		// If the version is specified, use the versioned values file.
+		if p.Version != "" {
+			p.ValuesFile = filepath.Join(p.ChartHome, fmt.Sprintf("%s-%s", p.Name, p.Version), p.Name, "values.yaml")
```
Comment (natasha41575) [inline plugin/builtin/helmchartinflationgenerator/HelmChartInflationGenerator.go:104]: nit: Could you convert lines 100-104 to an if/else? I think it will be easier to read that way

File: plugin/builtin/helmchartinflationgenerator/HelmChartInflationGenerator.go [hunk 2]
```diff
@@ -329,3 +334,12 @@ func (p *plugin) checkHelmVersion() error {
 	}
 	return nil
 }
+
+// chartPath will return the path to the chart and handle the case where a version
+// is specified
+func (p *plugin) chartPath() string {
+	if p.Version != "" {
+		return filepath.Join(p.absChartHome(), fmt.Sprintf("%s-%s", p.Name, p.Version))
```
Comment (natasha41575) [inline plugin/builtin/helmchartinflationgenerator/HelmChartInflationGenerator.go:342]: Instead of creating a new function `chartPath`, let's fold this if statement into `absChartHome` and have `absChartHome` return the path with the version.

File: plugin/builtin/helmchartinflationgenerator/HelmChartInflationGenerator_test.go [hunk 3]
```diff
@@ -579,3 +580,137 @@ valuesInline:
...
+repo: %s
+releaseName: %s
+`, tt.chartName, tt.chartName, tt.version, tt.repo, tt.releaseName)
+
+			rm := th.LoadAndRunGenerator(config)
+			assert.True(t, len(rm.Resources()) > 0)
+
+			chartDir := fmt.Sprintf("charts/%s", tt.chartName)
+			if tt.version != "" {
+				chartDir = fmt.Sprintf("charts/%s-%s/%s", tt.chartName, tt.version, tt.chartName)
```
Comment (natasha41575) [inline plugin/builtin/helmchartinflationgenerator/HelmChartInflationGenerator_test.go:647]: nit: Similar to above, let's convert lines 645-648 to an if/else for readability

**Review by natasha41575 — COMMENTED** [review]
PR is mostly looking good and tests look good to me! I have a few minor comments.

Thanks so much for working on this and for being so patient with our reviews.

File: plugin/builtin/helmchartinflationgenerator/HelmChartInflationGenerator.go (hunk 2 above)
Comment (dlish) [reply plugin/builtin/helmchartinflationgenerator/HelmChartInflationGenerator.go]: good call, made those changes here: https://github.com/kubernetes-sigs/kustomize/pull/4999/commits/380abb9e79ace1b03d15985e885e4b9e42c78ac7

File: plugin/builtin/helmchartinflationgenerator/HelmChartInflationGenerator.go (hunk 1 above)
Comment (dlish) [reply plugin/builtin/helmchartinflationgenerator/HelmChartInflationGenerator.go:102]: https://github.com/kubernetes-sigs/kustomize/pull/4999/commits/380abb9e79ace1b03d15985e885e4b9e42c78ac7

File: plugin/builtin/helmchartinflationgenerator/HelmChartInflationGenerator_test.go (hunk 3 above)
Comment (dlish) [reply plugin/builtin/helmchartinflationgenerator/HelmChartInflationGenerator_test.go:647]: https://github.com/kubernetes-sigs/kustomize/pull/4999/commits/380abb9e79ace1b03d15985e885e4b9e42c78ac7

**Comment by natasha41575** [comment]
/lgtm
/approve

Thank you so much for your contribution! Please feel free to reach out on the kubernetes slack if you are interested in picking up any other issues.

**Comment by seh** [comment]
Did the behavior change here so that now _kustomize_ always has Helm download a tar archive, even if the _charts_ directory already exists, populated with the content of the tar archive? Before version 5.0.2, _kustomize_ wouldn't try to download that archive again.

I find that if I download and then place the tar archive where _helm pull_ would put it, then the command fails, because the file already exists.

**Comment by seh** [comment]
Ah, the _Chart.yaml_ file now sits one directory component deeper, with the containing directory tree looking like the following:
```
charts
├── BUILD.bazel
└── minecraft-3.1.4
    └── minecraft
        ├── Chart.yaml
        ├── ...
        └── values.yaml
```
@dlish, what motivates repeating the chart name in the _minecraft_ directory within the _minecraft-3.1.4_ directory?
