### PR TITLE
[address #4717] Re-do create template/metadata when using includeTemplates if not present

### LINKED ISSUE #4717: includeTemplates doesn't work
**Describe the bug**

Labels aren't added to the pod metadata and the Deployment spec. `includeTemplates` has no effect.

**Files that can reproduce the issue**

kustomization.yaml

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: base-kustomization

commonLabels:
  app: test-server

labels:
  - pairs:
      app.kubernetes.io/name: test-server
      app.kubernetes.io/instance: test-server
      app.kubernetes.io/version: ${SERVER_VERSION}
      app.kubernetes.io/component: test
      app.kubernetes.io/part-of: test
      app.kubernetes.io/managed-by: test
      app.kubernetes.io/created-by: test
    includeTemplates: true

resources:
  - deployment.yaml
```

deployment.yaml

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-server
spec:
  replicas: 1
  template:
    metadata:
      name: test-server
    spec:
      restartPolicy: Always
      containers:
        - name: test-server
          image: test-server
          ports:
            - containerPort: 8080

```

**Expected output**

The Pod should have all defined labels from (`commonLabels` and `labels`).

**Actual output**

The Pod has only the labels from `commonLabels`. 

**Kustomize version**

{Version:kustomize/v4.5.5 GitCommit:daa3e5e2c2d3a4b8c94021a7384bfb06734bcd26 BuildDate:2022-05-20T20:25:40Z GoOs:linux GoArch:amd64}

**Platform**

Ubuntu 20.04 LTS inside WSL

### PR DESCRIPTION
**Pull request by aibarbetta**
Hi all, I'm attempting to re-do #4751 to fix #4717, I added a new test to reproduce the bug the old PR had.

It's not clear to me how can I add resource-specific fieldspecs for the `includeTemplates` flag in the labels plugin (as @KnVerey and @wolfmah mentioned [here](https://github.com/kubernetes-sigs/kustomize/pull/4751#issuecomment-1211073634) and [here](https://github.com/kubernetes-sigs/kustomize/pull/4751#issuecomment-1211125254)), can anyone provide some guidance?

Thanks!

### CODE REVIEW

**Comment by aibarbetta** [comment]
Thanks for the help @KnVerey! Changes are done, I added some tests for the rest of the types and they all pass. Can I get an ok-to-test to run the full suite here?

**Comment by aibarbetta** [comment]
@KnVerey make lint runs successfully now, can we retest? 🙏🏻

File: api/internal/plugins/builtinconfig/transformerconfig.go [hunk 1]
```diff
@@ -7,6 +7,7 @@ import (
 	"log"
 	"sort"
 
+	"github.com/pkg/errors"
```
Comment (koba1t) [inline api/internal/plugins/builtinconfig/transformerconfig.go:10]: `"github.com/pkg/errors"` looks like an already [unmaintained and archived](https://github.com/pkg/errors/issues/245).

Could you think of using `fmt.Errorf()` instead of `errors.Wrap()` if you don't have any reason?

Comment (aibarbetta) [reply api/internal/plugins/builtinconfig/transformerconfig.go]: > `"github.com/pkg/errors"` looks like an already [unmaintained and archived](https://github.com/pkg/errors/issues/245).
> 
> Could you think of using `fmt.Errorf()` instead of `errors.Wrap()` if you don't have any reason?

done! thanks for making me aware of that

**Comment by aibarbetta** [comment]
@KnVerey linter fix is done, can we retest?

**Comment by KnVerey** [comment]
Nice work! I have a couple very minor suggestions and will put a hold in case you want to take them (otherwise the bot will auto-merge immediately).

/hold
/lgtm
/approve

**Comment by aibarbetta** [comment]
> Nice work! I have a couple very minor suggestions and will put a hold in case you want to take them (otherwise the bot will auto-merge immediately).
> 
> /hold /lgtm /approve

Hi @KnVerey sure, please send me the suggestions

**Review by KnVerey — COMMENTED** [review]
Seems like I accidentally didn't click the submit button on this review. Sorry for the confusion!

**Comment by aibarbetta** [comment]
Thanks for the suggestions @KnVerey! all done :)

**Comment by KnVerey** [comment]
/unhold
/lgtm

Thank you for all your work on this one!
