### PR TITLE
Don't crash on resource load errors

### LINKED ISSUE #253: Kustomize crashes when a resource file is not found
Commands to reproduce (there must be no `deployment.yaml` file in the current directory):
```
$ cat >kustomization.yaml <<EOF
> resources:
> - deployment.yaml
> secretGenerator:
> - name: secret
>   commands:
>     PASSWORD: "printf pw"
>   type: Opaque
> EOF
$ kustomize build
panic: assignment to entry in nil map

goroutine 1 [running]:
github.com/kubernetes-sigs/kustomize/pkg/resmap.MergeWithOverride(0xc42020db70, 0x2, 0x2, 0xc420376ab0, 0x0, 0x0)
        /Users/ivan4th/work/kubernetes/src/github.com/kubernetes-sigs/kustomize/pkg/resmap/resmap.go:261 +0x80a
github.com/kubernetes-sigs/kustomize/pkg/app.(*Application).loadCustomizedResMap(0xc4204d6420, 0x72, 0x272, 0xc420108000)
        /Users/ivan4th/work/kubernetes/src/github.com/kubernetes-sigs/kustomize/pkg/app/application.go:164 +0x2f9
github.com/kubernetes-sigs/kustomize/pkg/app.(*Application).MakeCustomizedResMap(0xc4204d6420, 0xc4205029c0, 0x1cb4880, 0x2308630)
        /Users/ivan4th/work/kubernetes/src/github.com/kubernetes-sigs/kustomize/pkg/app/application.go:84 +0x2b
github.com/kubernetes-sigs/kustomize/pkg/commands.(*buildOptions).RunBuild(0xc4202d5b90, 0x1c96f80, 0xc42000e018, 0x1cb4880, 0x2308630, 0x1bbdefe, 0x4)
        /Users/ivan4th/work/kubernetes/src/github.com/kubernetes-sigs/kustomize/pkg/commands/build.go:101 +0x118
github.com/kubernetes-sigs/kustomize/pkg/commands.newCmdBuild.func1(0xc4200e8f00, 0x2308630, 0x0, 0x0, 0x0, 0x0)
        /Users/ivan4th/work/kubernetes/src/github.com/kubernetes-sigs/kustomize/pkg/commands/build.go:55 +0xaf
github.com/kubernetes-sigs/kustomize/vendor/github.com/spf13/cobra.(*Command).execute(0xc4200e8f00, 0x2308630, 0x0, 0x0, 0xc4200e8f00, 0x2308630)
        /Users/ivan4th/work/kubernetes/src/github.com/kubernetes-sigs/kustomize/vendor/github.com/spf13/cobra/command.go:756 +0x468
github.com/kubernetes-sigs/kustomize/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc4200e8500, 0xc4200e9400, 0xc4200e9680, 0xc42028c000)
        /Users/ivan4th/work/kubernetes/src/github.com/kubernetes-sigs/kustomize/vendor/github.com/spf13/cobra/command.go:846 +0x30a
github.com/kubernetes-sigs/kustomize/vendor/github.com/spf13/cobra.(*Command).Execute(0xc4200e8500, 0x1c34dc0, 0xc4200a0058)
        /Users/ivan4th/work/kubernetes/src/github.com/kubernetes-sigs/kustomize/vendor/github.com/spf13/cobra/command.go:794 +0x2b
main.main()
        /Users/ivan4th/work/kubernetes/src/github.com/kubernetes-sigs/kustomize/kustomize.go:30 +0x43
```

### PR DESCRIPTION
**Pull request by ivan4th**
In case if a non-existent file is referenced among `resources` in `kustomization.yaml`, kustomize panics with the following stack trace:
```
panic: assignment to entry in nil map

goroutine 1 [running]:
github.com/kubernetes-sigs/kustomize/pkg/resmap.MergeWithOverride(0xc4202eb438, 0x2, 0x2, 0xc420376570, 0x0, 0x0)
        /Users/ivan4th/work/kubernetes/src/github.com/kubernetes-sigs/kustomize/pkg/resmap/resmap.go:261 +0x80a
github.com/kubernetes-sigs/kustomize/pkg/app.(*Application).loadCustomizedResMap(0xc42028d260, 0xc4204e4340, 0x1cb46e0, 0x2308630)
        /Users/ivan4th/work/kubernetes/src/github.com/kubernetes-sigs/kustomize/pkg/app/application.go:163 +0x2d7
github.com/kubernetes-sigs/kustomize/pkg/app.(*Application).loadCustomizedBases(0xc42027a120, 0x1011fe9, 0xc4205030e0)
        /Users/ivan4th/work/kubernetes/src/github.com/kubernetes-sigs/kustomize/pkg/app/application.go:227 +0x424
github.com/kubernetes-sigs/kustomize/pkg/app.(*Application).loadResMapFromBasesAndResources(0xc42027a120, 0xc4205030e0, 0xc420400200, 0x1a36c60)
        /Users/ivan4th/work/kubernetes/src/github.com/kubernetes-sigs/kustomize/pkg/app/application.go:198 +0x40
github.com/kubernetes-sigs/kustomize/pkg/app.(*Application).loadCustomizedResMap(0xc42027a120, 0xc420502b80, 0x1cb46e0, 0x2308630)
        /Users/ivan4th/work/kubernetes/src/github.com/kubernetes-sigs/kustomize/pkg/app/application.go:138 +0x60
github.com/kubernetes-sigs/kustomize/pkg/app.(*Application).loadCustomizedBases(0xc4204d9cb0, 0x1011fe9, 0xc420502b40)
        /Users/ivan4th/work/kubernetes/src/github.com/kubernetes-sigs/kustomize/pkg/app/application.go:227 +0x424
github.com/kubernetes-sigs/kustomize/pkg/app.(*Application).loadResMapFromBasesAndResources(0xc4204d9cb0, 0xc420502b40, 0xc4202eba80, 0x11a00ff)
        /Users/ivan4th/work/kubernetes/src/github.com/kubernetes-sigs/kustomize/pkg/app/application.go:198 +0x40
github.com/kubernetes-sigs/kustomize/pkg/app.(*Application).loadCustomizedResMap(0xc4204d9cb0, 0x1b, 0x21b, 0xc4204e2000)
        /Users/ivan4th/work/kubernetes/src/github.com/kubernetes-sigs/kustomize/pkg/app/application.go:138 +0x60
github.com/kubernetes-sigs/kustomize/pkg/app.(*Application).MakeCustomizedResMap(0xc4204d9cb0, 0xc420502960, 0x1cb46e0, 0x2308630)
        /Users/ivan4th/work/kubernetes/src/github.com/kubernetes-sigs/kustomize/pkg/app/application.go:83 +0x2b
github.com/kubernetes-sigs/kustomize/pkg/commands.(*buildOptions).RunBuild(0xc4205025a0, 0x1c96de0, 0xc42000e018, 0x1cb46e0, 0x2308630, 0x1bbdd3e, 0x4)
        /Users/ivan4th/work/kubernetes/src/github.com/kubernetes-sigs/kustomize/pkg/commands/build.go:95 +0x10a
github.com/kubernetes-sigs/kustomize/pkg/commands.newCmdBuild.func1(0xc4200e6f00, 0x2308630, 0x0, 0x0, 0x0, 0x0)
        /Users/ivan4th/work/kubernetes/src/github.com/kubernetes-sigs/kustomize/pkg/commands/build.go:53 +0xaf
github.com/kubernetes-sigs/kustomize/vendor/github.com/spf13/cobra.(*Command).execute(0xc4200e6f00, 0x2308630, 0x0, 0x0, 0xc4200e6f00, 0x2308630)
        /Users/ivan4th/work/kubernetes/src/github.com/kubernetes-sigs/kustomize/vendor/github.com/spf13/cobra/command.go:756 +0x468
github.com/kubernetes-sigs/kustomize/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc4200e6500, 0xc4200e7400, 0xc4200e7680, 0xc420286000)
        /Users/ivan4th/work/kubernetes/src/github.com/kubernetes-sigs/kustomize/vendor/github.com/spf13/cobra/command.go:846 +0x30a
github.com/kubernetes-sigs/kustomize/vendor/github.com/spf13/cobra.(*Command).Execute(0xc4200e6500, 0x1c34be8, 0xc4200440b8)
        /Users/ivan4th/work/kubernetes/src/github.com/kubernetes-sigs/kustomize/vendor/github.com/spf13/cobra/command.go:794 +0x2b
main.main()
        /Users/ivan4th/work/kubernetes/src/github.com/kubernetes-sigs/kustomize/kustomize.go:30 +0x43
```

This happens because kustomize tries to proceed even after a file load error occurs, but fails to deal with nil `ResMap` properly.

Fixes #253

### CODE REVIEW

**Comment by Liujingfang1** [comment]
I'll take a look later.

File: pkg/resmap/resmap.go [hunk 1]
```diff
@@ -226,14 +230,25 @@ func MergeWithoutOverride(maps ...ResMap) (ResMap, error) {
...
 func MergeWithOverride(maps ...ResMap) (ResMap, error) {
 	result := maps[0]
+	if result == nil {
+		result = ResMap{}
+	}
 	for _, m := range maps[1:] {
+		if m == nil {
+			continue
+		}
+		if result == nil {
```
Comment (monopole) [inline pkg/resmap/resmap.go]: how can this be true given L242?

File: pkg/resmap/resmap.go [hunk 2]
```diff
@@ -265,6 +280,9 @@ func MergeWithOverride(maps ...ResMap) (ResMap, error) {
 			}
 		}
 	}
+	if result == nil {
+		return ResMap{}, nil
```
Comment (monopole) [inline pkg/resmap/resmap.go]: Ditto

File: pkg/app/application_test.go [hunk 3]
```diff
@@ -197,6 +198,27 @@ func TestResources1(t *testing.T) {
...
+	}
+	_, err = app.MakeCustomizedResMap()
+	if err == nil {
+		t.Fatalf("Didn't get the expected error for an unknown resource")
+	}
+	if !strings.Contains(err.Error(), `cannot read file "/testpath/deployment.yaml"`) {
+		t.Fatalf("Unpexpected error message %q", err)
+	}
+}
+
```
Comment (monopole) [inline pkg/app/application_test.go]: thanks, this better than panic

File: pkg/resmap/resmap.go (hunk 1 above)
Comment (ivan4th) [reply pkg/resmap/resmap.go]: Oops, leftover from a previous attempt. Removed.

File: pkg/resmap/resmap.go (hunk 2 above)
Comment (ivan4th) [reply pkg/resmap/resmap.go]: Same as above. Fixed.
