### PR TITLE
fixed ports merging issue and refactored some kyaml/walk code

### LINKED ISSUE #3513: StrategicMergePatch messes up the ports
StrategicMergePatch messes up the ports, when there are multiple protocols for the same port. 
I tested this on `3.9.2`:

# kustomization.yaml

```
resources:
  - resource.yaml
patches:
  - path: patch.yaml
    target:
      kind: StatefulSet
      name: myapp
```

# resource.yaml

```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: myapp
spec:
  template:
    spec:
      containers:
        - name: consul
          image: "hashicorp/consul:1.9.1"
          ports:
            - containerPort: 8500
              name: http
            - containerPort: 8501
              name: https
            - containerPort: 8301
              protocol: "TCP"
              name: serflan-tcp
            - containerPort: 8301
              protocol: "UDP"
              name: serflan-udp
            - containerPort: 8302
              name: serfwan
            - containerPort: 8300
              name: server
            - containerPort: 8600
              name: dns-tcp
              protocol: "TCP"
            - containerPort: 8600
              name: dns-udp
              protocol: "UDP"
```

# patch.yalm

```
kind: StatefulSet
metadata:
  name: myapp
  labels:
    test: label
```

# Result:

```
kustomize build .
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    test: label
  name: myapp
spec:
  template:
    spec:
      containers:
      - image: hashicorp/consul:1.9.1
        name: consul
        ports:
        - containerPort: 8500
          name: http
        - containerPort: 8501
          name: https
        - containerPort: 8301
          name: serflan-udp
          protocol: UDP
        - containerPort: 8301
          name: serflan-udp
          protocol: UDP
        - containerPort: 8302
          name: serfwan
        - containerPort: 8300
          name: server
        - containerPort: 8600
          name: dns-udp
          protocol: UDP
        - containerPort: 8600
          name: dns-udp
          protocol: UDP
```

### PR DESCRIPTION
**Pull request by natasha41575**
Fix #3513 

Includes some kyaml/walk refactoring and a small API change to the behavior of ElementSetter

ALLOW_MODULE_SPAN

### CODE REVIEW

File: kyaml/yaml/walk/associative_sequence.go [hunk 1]
```diff
@@ -278,7 +223,7 @@ func (l *Walker) walkAssociativeSequence() (*yaml.RNode, error) {
 	}
 
 	// primitive associative list -- merge the values
```
Comment (monopole) [inline kyaml/yaml/walk/associative_sequence.go:225]: so `setPrimitiveSequenceElements` is dropped in favor of `setAssociativeSequenceElements`, and `elementValue` is dropped, leaving only `elementPrimitiveValue`.

Is there some point to the word _primitive_ any more?  I don't see it.

Comment (natasha41575) [reply kyaml/yaml/walk/associative_sequence.go:225]: There were three functions:
elementValue (used only by setPrimitiveSequenceElements)
elementValues - used to get values given a set of keys
elementPrimitiveValues - used to get values from a primitive list

setAssociativeSequenceElements and setPrimitiveSequenceElements were similar enough that a tweak to elementPrimitiveValues meant it could use setAssociativeSequenceElements instead

However, there is still a distinction between elementValues and elementPrimitiveValues that I think is important to keep
